apiVersion: apps/v1
kind: Deployment
metadata:
  name: jerseyhub
  labels:
    app: jerseyhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jerseyhub
  template:
    metadata:
      labels:
        app: jerseyhub
    spec:
      containers:
        - name: jerseyhub
          image: arunkarun/jerseyhub:v1.0
          ports:
            - containerPort: 3000
          env:
            - name: DB_USER
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: DB_NAME
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-congifmap
                  key: postgres-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-congifmap
                  key: postgres-port
---
apiVersion: v1
kind: Service
metadata:
  name: jerseyhub-service
spec:
  selector:
    app: jerseyhub
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001  